<?php

declare(strict_types=1);

/**
 * DisMoi OpenAPI.
 *
 * OpenAPI documentation and _sandbox_ for **DisMoi** (_Tell Me_ in french), a FLOSS web annotations project to turn the tide of the opinion wars back in favor of the internauts.  - [Official Website](https://www.dismoi.io/) - [Source Code](https://github.com/dis-moi) - [Report Issues](https://github.com/dis-moi/backend/issues) (_please!_)
 *
 * The version of the OpenAPI document: 4.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 *
 * This class is auto generated, do not edit manually.
 */

namespace DisMoi\Client\Model;

use ArrayAccess;
use DisMoi\Client\ObjectSerializer;

/**
 * MatchingContextRead Class Doc Comment.
 *
 * @category Class
 * @description A MatchingContext pinpoints a set of web pages on the internet.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class MatchingContextRead implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MatchingContext-read';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'exampleUrl' => 'string',
        'urlRegex' => 'string',
        'excludeUrlRegex' => 'string',
        'description' => 'string',
        'querySelector' => 'string',
        'xpath' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'exampleUrl' => null, 'urlRegex' => null, 'excludeUrlRegex' => null, 'description' => null, 'querySelector' => null, 'xpath' => null,
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'exampleUrl' => 'exampleUrl',
        'urlRegex' => 'urlRegex',
        'excludeUrlRegex' => 'excludeUrlRegex',
        'description' => 'description',
        'querySelector' => 'querySelector',
        'xpath' => 'xpath',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'exampleUrl' => 'setExampleUrl',
        'urlRegex' => 'setUrlRegex',
        'excludeUrlRegex' => 'setExcludeUrlRegex',
        'description' => 'setDescription',
        'querySelector' => 'setQuerySelector',
        'xpath' => 'setXpath',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'exampleUrl' => 'getExampleUrl',
        'urlRegex' => 'getUrlRegex',
        'excludeUrlRegex' => 'getExcludeUrlRegex',
        'description' => 'getDescription',
        'querySelector' => 'getQuerySelector',
        'xpath' => 'getXpath',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['exampleUrl'] = $data[self::$attributeMap['exampleUrl']] ?? null;
        $this->container['urlRegex'] = $data[self::$attributeMap['urlRegex']] ?? null;
        $this->container['excludeUrlRegex'] = $data[self::$attributeMap['excludeUrlRegex']] ?? null;
        $this->container['description'] = $data[self::$attributeMap['description']] ?? null;
        $this->container['querySelector'] = $data[self::$attributeMap['querySelector']] ?? null;
        $this->container['xpath'] = $data[self::$attributeMap['xpath']] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (null === $this->container['urlRegex']) {
            $invalidProperties[] = "'urlRegex' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === \count($this->listInvalidProperties());
    }

    /**
     * Gets exampleUrl.
     *
     * @return string|null
     */
    public function getExampleUrl()
    {
        return $this->container['exampleUrl'];
    }

    /**
     * Sets exampleUrl.
     *
     * @param string|null $exampleUrl exampleUrl
     *
     * @return self
     */
    public function setExampleUrl($exampleUrl)
    {
        $this->container['exampleUrl'] = $exampleUrl;

        return $this;
    }

    /**
     * Gets urlRegex.
     *
     * @return string
     */
    public function getUrlRegex()
    {
        return $this->container['urlRegex'];
    }

    /**
     * Sets urlRegex.
     *
     * @param string $urlRegex urlRegex
     *
     * @return self
     */
    public function setUrlRegex($urlRegex)
    {
        $this->container['urlRegex'] = $urlRegex;

        return $this;
    }

    /**
     * Gets excludeUrlRegex.
     *
     * @return string|null
     */
    public function getExcludeUrlRegex()
    {
        return $this->container['excludeUrlRegex'];
    }

    /**
     * Sets excludeUrlRegex.
     *
     * @param string|null $excludeUrlRegex excludeUrlRegex
     *
     * @return self
     */
    public function setExcludeUrlRegex($excludeUrlRegex)
    {
        $this->container['excludeUrlRegex'] = $excludeUrlRegex;

        return $this;
    }

    /**
     * Gets description.
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description.
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets querySelector.
     *
     * @return string|null
     */
    public function getQuerySelector()
    {
        return $this->container['querySelector'];
    }

    /**
     * Sets querySelector.
     *
     * @param string|null $querySelector a CSS selector
     *
     * @return self
     */
    public function setQuerySelector($querySelector)
    {
        $this->container['querySelector'] = $querySelector;

        return $this;
    }

    /**
     * Gets xpath.
     *
     * @return string|null
     */
    public function getXpath()
    {
        return $this->container['xpath'];
    }

    /**
     * Sets xpath.
     *
     * @param string|null $xpath an XPath expression
     *
     * @return self
     */
    public function setXpath($xpath)
    {
        $this->container['xpath'] = $xpath;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            \JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
