<?php

declare(strict_types=1);

/**
 * DisMoi OpenAPI.
 *
 * OpenAPI documentation and _sandbox_ for **DisMoi** (_Tell Me_ in french), a FLOSS web annotations project to turn the tide of the opinion wars back in favor of the internauts.  - [Official Website](https://www.dismoi.io/) - [Source Code](https://github.com/dis-moi) - [Report Issues](https://github.com/dis-moi/backend/issues) (_please!_)
 *
 * The version of the OpenAPI document: 4.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 *
 * This class is auto generated, do not edit manually.
 */

namespace DisMoi\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse200HydraSearchTest Class Doc Comment.
 *
 * @category    Class
 * @description InlineResponse200HydraSearch
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class InlineResponse200HydraSearchTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse200HydraSearch".
     */
    public function testInlineResponse200HydraSearch(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydra:template".
     */
    public function testPropertyTemplate(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydra:variableRepresentation".
     */
    public function testPropertyVariableRepresentation(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hydra:mapping".
     */
    public function testPropertyMapping(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
