<?php

declare(strict_types=1);

/**
 * DisMoi OpenAPI.
 *
 * OpenAPI documentation and _sandbox_ for **DisMoi** (_Tell Me_ in french), a FLOSS web annotations project to turn the tide of the opinion wars back in favor of the internauts.  - [Official Website](https://www.dismoi.io/) - [Source Code](https://github.com/dis-moi) - [Report Issues](https://github.com/dis-moi/backend/issues) (_please!_)
 *
 * The version of the OpenAPI document: 4.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 *
 * This class is auto generated, do not edit manually.
 */

namespace DisMoi\Client\Test\Api;

use PHPUnit\Framework\TestCase;

/**
 * NoticeApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class NoticeApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiNoticesMatchingContextsGetSubresourceNoticeSubresource.
     *
     * Retrieves a Notice resource..
     */
    public function testApiNoticesMatchingContextsGetSubresourceNoticeSubresource(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNoticeItem.
     *
     * Removes the Notice resource..
     */
    public function testDeleteNoticeItem(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNoticeCollection.
     *
     * Retrieves the collection of Notice resources..
     */
    public function testGetNoticeCollection(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNoticeItem.
     *
     * Retrieves a Notice resource..
     */
    public function testGetNoticeItem(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postNoticeCollection.
     *
     * Creates a Notice resource..
     */
    public function testPostNoticeCollection(): void
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
